<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>direct_all_button</name>
   <tag></tag>
   <elementGuidId>993c7bc3-aaaa-44cb-9333-ce94bc5fc232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;accountView&quot;]/div/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
