<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>marketplace_redirection_catalogs</name>
   <tag></tag>
   <elementGuidId>e620ad0d-035e-48c9-8fd6-ed9bbd8a404c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.menu-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
